const mongoose = require('mongoose');

const WeeklyBudgetSchema = new mongoose.Schema({
  userId: { type: String, required: true, index: true },
  
  // Week identification
  weekStartDate: { type: Date, required: true }, // Monday of the week
  weekEndDate: { type: Date, required: true },   // Sunday of the week
  weekNumber: { type: Number, required: true },   // Week number in year
  year: { type: Number, required: true },
  
  // Budget categories with current spending and max limits
  categories: {
    food: {
      currentSpentPaise: { type: Number, default: 0 },
      maxBudgetPaise: { type: Number, default: 170000 }, // ₹1700 (AI will update)
      transactionCount: { type: Number, default: 0 },
      riskScore: { type: Number, min: 0, max: 100, default: 0 },
      status: { type: String, enum: ['safe', 'warning', 'over_budget'], default: 'safe' }
    },
    fuel: {
      currentSpentPaise: { type: Number, default: 0 },
      maxBudgetPaise: { type: Number, default: 80000 }, // ₹800
      transactionCount: { type: Number, default: 0 },
      riskScore: { type: Number, min: 0, max: 100, default: 0 },
      status: { type: String, enum: ['safe', 'warning', 'over_budget'], default: 'safe' }
    },
    transport: {
      currentSpentPaise: { type: Number, default: 0 },
      maxBudgetPaise: { type: Number, default: 30000 }, // ₹300
      transactionCount: { type: Number, default: 0 },
      riskScore: { type: Number, min: 0, max: 100, default: 0 },
      status: { type: String, enum: ['safe', 'warning', 'over_budget'], default: 'safe' }
    },
    recharge: {
      currentSpentPaise: { type: Number, default: 0 },
      maxBudgetPaise: { type: Number, default: 25000 }, // ₹250
      transactionCount: { type: Number, default: 0 },
      riskScore: { type: Number, min: 0, max: 100, default: 0 },
      status: { type: String, enum: ['safe', 'warning', 'over_budget'], default: 'safe' }
    },
    miscellaneous: {
      currentSpentPaise: { type: Number, default: 0 },
      maxBudgetPaise: { type: Number, default: 50000 }, // ₹500
      transactionCount: { type: Number, default: 0 },
      riskScore: { type: Number, min: 0, max: 100, default: 0 },
      status: { type: String, enum: ['safe', 'warning', 'over_budget'], default: 'safe' }
    },
    entertainment: {
      currentSpentPaise: { type: Number, default: 0 },
      maxBudgetPaise: { type: Number, default: 20000 }, // ₹200
      transactionCount: { type: Number, default: 0 },
      riskScore: { type: Number, min: 0, max: 100, default: 0 },
      status: { type: String, enum: ['safe', 'warning', 'over_budget'], default: 'safe' }
    },
    medical: {
      currentSpentPaise: { type: Number, default: 0 },
      maxBudgetPaise: { type: Number, default: 30000 }, // ₹300
      transactionCount: { type: Number, default: 0 },
      riskScore: { type: Number, min: 0, max: 100, default: 0 },
      status: { type: String, enum: ['safe', 'warning', 'over_budget'], default: 'safe' }
    },
    send_home: {
      currentSpentPaise: { type: Number, default: 0 },
      maxBudgetPaise: { type: Number, default: 120000 }, // ₹1200
      transactionCount: { type: Number, default: 0 },
      riskScore: { type: Number, min: 0, max: 100, default: 0 },
      status: { type: String, enum: ['safe', 'warning', 'over_budget'], default: 'safe' }
    }
  },
  
  // Overall week summary
  totalSpentPaise: { type: Number, default: 0 },
  totalBudgetPaise: { type: Number, default: 0 },
  overallRiskScore: { type: Number, min: 0, max: 100, default: 0 },
  budgetUtilization: { type: Number, min: 0, max: 100, default: 0 }, // percentage used
  
  // Week metadata
  isAutoGenerated: { type: Boolean, default: true },
  lastUpdated: { type: Date, default: Date.now },
  aiLastAnalyzed: { type: Date, default: null },
  aiSummary: { type: String, default: '' }, // AI-generated weekly budget summary
  
  // Budget adjustment flags
  adjustmentFlags: {
    incomeDropDetected: { type: Boolean, default: false },
    incomeSpike: { type: Boolean, default: false },
    festivalMonth: { type: Boolean, default: false },
    emergencySpend: { type: Boolean, default: false },
    cashFluctuation: { type: Boolean, default: false },
    emiDueDate: { type: Boolean, default: false }
  },
  
  // Transaction summary for the week
  transactionSummary: {
    totalTransactions: { type: Number, default: 0 },
    incomeTransactions: { type: Number, default: 0 },
    expenseTransactions: { type: Number, default: 0 },
    avgTransactionPaise: { type: Number, default: 0 },
    largestExpensePaise: { type: Number, default: 0 },
    mostActiveCategory: { type: String, default: 'food' }
  }
}, {
  timestamps: true
});

// Indexes for efficient queries
WeeklyBudgetSchema.index({ userId: 1, weekStartDate: -1 });
WeeklyBudgetSchema.index({ userId: 1, year: 1, weekNumber: 1 });
WeeklyBudgetSchema.index({ weekStartDate: 1, weekEndDate: 1 });

// Virtual for week identifier
WeeklyBudgetSchema.virtual('weekId').get(function() {
  return `${this.year}-W${this.weekNumber.toString().padStart(2, '0')}`;
});

// Method to calculate risk score for a category
WeeklyBudgetSchema.methods.calculateCategoryRiskScore = function(categoryName) {
  const category = this.categories[categoryName];
  if (!category || category.maxBudgetPaise === 0) return 0;
  
  const utilizationPercent = (category.currentSpentPaise / category.maxBudgetPaise) * 100;
  
  // Risk score calculation
  if (utilizationPercent <= 50) return Math.round(utilizationPercent * 0.4); // 0-20
  if (utilizationPercent <= 80) return Math.round(20 + (utilizationPercent - 50) * 1.0); // 20-50
  if (utilizationPercent <= 100) return Math.round(50 + (utilizationPercent - 80) * 1.5); // 50-80
  return Math.min(100, Math.round(80 + (utilizationPercent - 100) * 0.5)); // 80-100
};

// Method to update category status based on spending
WeeklyBudgetSchema.methods.updateCategoryStatus = function(categoryName) {
  const category = this.categories[categoryName];
  if (!category) return;
  
  const utilizationPercent = (category.currentSpentPaise / category.maxBudgetPaise) * 100;
  
  if (utilizationPercent >= 100) {
    category.status = 'over_budget';
  } else if (utilizationPercent >= 80) {
    category.status = 'warning';
  } else {
    category.status = 'safe';
  }
  
  // Update risk score
  category.riskScore = this.calculateCategoryRiskScore(categoryName);
};

// Method to calculate overall budget metrics
WeeklyBudgetSchema.methods.calculateOverallMetrics = function() {
  const categories = this.categories;
  
  // Calculate totals
  this.totalSpentPaise = Object.values(categories).reduce((sum, cat) => sum + cat.currentSpentPaise, 0);
  this.totalBudgetPaise = Object.values(categories).reduce((sum, cat) => sum + cat.maxBudgetPaise, 0);
  
  // Calculate utilization percentage
  this.budgetUtilization = this.totalBudgetPaise > 0 ? 
    Math.round((this.totalSpentPaise / this.totalBudgetPaise) * 100) : 0;
  
  // Calculate overall risk score (weighted by budget allocation)
  let weightedRiskSum = 0;
  let totalWeight = 0;
  
  Object.entries(categories).forEach(([name, category]) => {
    const weight = category.maxBudgetPaise;
    weightedRiskSum += category.riskScore * weight;
    totalWeight += weight;
  });
  
  this.overallRiskScore = totalWeight > 0 ? Math.round(weightedRiskSum / totalWeight) : 0;
  this.lastUpdated = new Date();
};

// Static method to get current week's budget for user
WeeklyBudgetSchema.statics.getCurrentWeekBudget = function(userId) {
  const now = new Date();
  const startOfWeek = new Date(now);
  startOfWeek.setDate(now.getDate() - now.getDay() + 1); // Monday
  startOfWeek.setHours(0, 0, 0, 0);
  
  return this.findOne({
    userId,
    weekStartDate: startOfWeek
  });
};

// Static method to create week dates
WeeklyBudgetSchema.statics.getWeekDates = function(date = new Date()) {
  const startOfWeek = new Date(date);
  startOfWeek.setDate(date.getDate() - date.getDay() + 1); // Monday
  startOfWeek.setHours(0, 0, 0, 0);
  
  const endOfWeek = new Date(startOfWeek);
  endOfWeek.setDate(startOfWeek.getDate() + 6); // Sunday
  endOfWeek.setHours(23, 59, 59, 999);
  
  // Get week number
  const firstDayOfYear = new Date(date.getFullYear(), 0, 1);
  const pastDaysOfYear = (startOfWeek - firstDayOfYear) / 86400000;
  const weekNumber = Math.ceil((pastDaysOfYear + firstDayOfYear.getDay() + 1) / 7);
  
  return {
    weekStartDate: startOfWeek,
    weekEndDate: endOfWeek,
    weekNumber,
    year: date.getFullYear()
  };
};

// Enhanced method to map transaction category to budget category with smart detection
WeeklyBudgetSchema.statics.mapTransactionCategory = function(transactionCategory, merchant = '', description = '') {
  const categoryMap = {
    'food': 'food',
    'fuel': 'fuel',
    'transport': 'transport',
    'recharge': 'recharge',
    'phone_bill': 'recharge',
    'medical': 'medical',
    'send_home': 'send_home',
    'entertainment': 'entertainment',
    'bike_repair': 'miscellaneous',
    'other': 'miscellaneous'
  };
  
  // If category is already mapped, return it
  if (categoryMap[transactionCategory]) {
    return categoryMap[transactionCategory];
  }
  
  // Smart merchant-based categorization
  const merchantLower = (merchant || '').toLowerCase();
  const descriptionLower = (description || '').toLowerCase();
  const combinedText = `${merchantLower} ${descriptionLower}`;
  
  // Food merchants
  if (combinedText.includes('swiggy') || combinedText.includes('zomato') || 
      combinedText.includes('restaurant') || combinedText.includes('food') ||
      combinedText.includes('cafe') || combinedText.includes('hotel') ||
      combinedText.includes('dominos') || combinedText.includes('kfc') ||
      combinedText.includes('mcdonalds') || combinedText.includes('grocery')) {
    return 'food';
  }
  
  // Fuel merchants  
  if (combinedText.includes('petrol') || combinedText.includes('fuel') ||
      combinedText.includes('hp') || combinedText.includes('iocl') ||
      combinedText.includes('bharat petroleum') || combinedText.includes('bpcl') ||
      combinedText.includes('shell') || combinedText.includes('reliance petroleum')) {
    return 'fuel';
  }
  
  // Transport merchants
  if (combinedText.includes('uber') || combinedText.includes('ola') ||
      combinedText.includes('metro') || combinedText.includes('bus') ||
      combinedText.includes('train') || combinedText.includes('taxi') ||
      combinedText.includes('auto') || combinedText.includes('rapido')) {
    return 'transport';
  }
  
  // Recharge merchants
  if (combinedText.includes('recharge') || combinedText.includes('jio') ||
      combinedText.includes('airtel') || combinedText.includes('vi') ||
      combinedText.includes('bsnl') || combinedText.includes('phone') ||
      combinedText.includes('mobile') || combinedText.includes('prepaid') ||
      combinedText.includes('postpaid')) {
    return 'recharge';
  }
  
  // Medical merchants
  if (combinedText.includes('medical') || combinedText.includes('hospital') ||
      combinedText.includes('pharmacy') || combinedText.includes('clinic') ||
      combinedText.includes('apollo') || combinedText.includes('fortis') ||
      combinedText.includes('medicine') || combinedText.includes('doctor')) {
    return 'medical';
  }
  
  // Entertainment merchants
  if (combinedText.includes('netflix') || combinedText.includes('amazon prime') ||
      combinedText.includes('youtube') || combinedText.includes('spotify') ||
      combinedText.includes('movie') || combinedText.includes('cinema') ||
      combinedText.includes('game') || combinedText.includes('entertainment')) {
    return 'entertainment';
  }
  
  // Send home indicators
  if (combinedText.includes('transfer') || combinedText.includes('family') ||
      combinedText.includes('home') || combinedText.includes('parent') ||
      combinedText.includes('mother') || combinedText.includes('father')) {
    return 'send_home';
  }
  
  // Default to miscellaneous
  return categoryMap[transactionCategory] || 'miscellaneous';
};

// Pre-save middleware to update all calculations
WeeklyBudgetSchema.pre('save', function(next) {
  // Update all category statuses and risk scores
  Object.keys(this.categories).forEach(categoryName => {
    this.updateCategoryStatus(categoryName);
  });
  
  // Calculate overall metrics
  this.calculateOverallMetrics();
  
  next();
});

module.exports = mongoose.model('WeeklyBudget', WeeklyBudgetSchema);